const test = require('node:test');
const { before } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { spawnSync } = require('node:child_process');

const exampleDir = path.resolve(__dirname, '../example');
const bookDir = path.join(exampleDir, '_book');
const indexPath = path.join(bookDir, 'search_index.json');

function run(cmd, args) {
  const result = spawnSync(cmd, args, {
    cwd: exampleDir,
    stdio: 'inherit',
  });
  if (result.status !== 0) {
    throw new Error(`${cmd} ${args.join(' ')} failed with status ${result.status}`);
  }
}

function loadDocs() {
  const raw = fs.readFileSync(indexPath, 'utf8');
  const lines = raw.split('\n').filter((l) => l.length > 0);
  assert.equal(lines.length % 2, 0, 'NDJSON should have an even number of lines');
  const docs = [];
  for (let i = 0; i < lines.length; i += 2) {
    const action = JSON.parse(lines[i]);
    assert.ok('index' in action, `line ${i + 1} should be an "index" action`);
    docs.push(JSON.parse(lines[i + 1]));
  }
  return docs;
}

before(() => {
  // Always rebuild from a clean state so the test reflects the current plugin code.
  // Dependencies are assumed to be installed by `pnpm install` at the workspace root.
  fs.rmSync(bookDir, { recursive: true, force: true });
  run('pnpm', ['exec', 'honkit', 'build']);

  assert.ok(fs.existsSync(indexPath), `${indexPath} was not generated by honkit build`);
});

test('search_index.json: bulk format', async (t) => {
  let docs;

  await t.test('file exists and is non-empty', () => {
    docs = loadDocs();
    assert.ok(docs.length > 0, 'index must contain documents');
  });

  await t.test('every doc has required fields', () => {
    for (const doc of docs) {
      for (const key of ['url', 'title', 'keywords', 'body']) {
        assert.ok(key in doc, `doc "${doc.title}" missing field "${key}"`);
      }
    }
  });

  await t.test('expected pages are indexed (skipped.md excluded)', () => {
    const titles = docs.map((d) => d.title).sort();
    assert.deepEqual(titles, ['Introduction', 'Page One', 'Page Two']);
  });

  await t.test('keywords from YAML front-matter are preserved', () => {
    const pageOne = docs.find((d) => d.title === 'Page One');
    assert.equal(pageOne.keywords, 'alpha bravo');
  });

  await t.test('HTML tags are stripped from body', () => {
    const pageTwo = docs.find((d) => d.title === 'Page Two');
    assert.ok(!/<[^>]+>/.test(pageTwo.body), `unexpected HTML in body: ${pageTwo.body}`);
  });

  await t.test('HTML entities are decoded', () => {
    const pageTwo = docs.find((d) => d.title === 'Page Two');
    assert.ok(!pageTwo.body.includes('&amp;'), 'entities must be decoded');
    assert.ok(pageTwo.body.includes('&'), 'decoded ampersand expected');
  });
});
